export const UPLOAD_EMPLOYEE_TYPE = "UPLOAD_EMPLOYEE"
export const UPLOAD_DATA_TYPE = "UPLOAD_DATA";
export const UPLOAD_EMPLOYEE_FAIL = "UPLOAD_EMPLOYEE_FAIL";
export const UPLOAD_EMPLOYEE_SUCCESS = "UPLOAD_EMPLOYEE_SUCCESS"